site_name: Terrorluv
site_url: https://terrorluv.vercel.app
theme:
  name: material
  palette:
    primary: pink
    accent: red

plugins:
  - privacy:
      links_attr_map:
        target: _blank

extra_javascript:
  - javascripts/extra.js
  - javascripts/load-sheets.js
  - javascripts/hyperscript.min.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - https://unpkg.com/tablesort@5.3.0/dist/sorts/tablesort.number.min.js

  #- javascripts/tablesort.js

extra_css:
  - stylesheets/extra.css
  - stylesheets/hyperscript.css
  
markdown_extensions: 
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg